# Variables
@baseUrl = http://localhost:3333

# Health check
# @name healtCheck

GET {{baseUrl}}/health

###

# Get All Users
# @name getAllUsers
GET {{baseUrl}}/users

###

# Get All Users With query name
# @name getAllUsers
GET {{baseUrl}}/users?page=1&page_size=5


###

# Get All Users With query role
# @name getAllUsers
GET {{baseUrl}}/users?&role=admin

###

# Get All Users With query active
# @name getAllUsers
GET {{baseUrl}}/users?&is_active=false

###

# Get User by Id
# @name getUserById
GET {{baseUrl}}/users/10